### ISSUE TITLE
Possible to use as a library?

### ISSUE THREAD

**Issue by ineiti** [colourful-rtc/turn-rs#57]
Hi there,

I'm looking for a TURN and a STUN server to add to my project. Is it possible to use your server as a library?

**Comment by mycrl** [comment]
> Hi there,
> 
> I'm looking for a TURN and a STUN server to add to my project. Is it possible to use your server as a library?

only the stun module can be used as a library, the turn is related to the network and is currently independent.

Or, you can simply describe your needs, do you just want to handle the turn protocol process through the turn library?

turn depends on session management and network, of course, I can expose the two parts of network and authentication.

**Comment by ineiti** [comment]
Thanks for your quick response. I currently run my WebRTC signalling server alongside `coturn` for the STUN/TURN services using 
[docker-compose](https://github.com/ineiti/fledger/blob/main/examples/docker-compose/docker-compose.signalling.yaml). 
Ideally I would like to include the STUN/TURN services directly in my signalling server, so all is in one binary.
Currently I have a simple username/password authentication for the TURN.

So in the best case, I would be able to start a STUN server and give the username/password to start a TURN server.

**Comment by mycrl** [comment]
> Thanks for your quick response. I currently run my WebRTC signalling server alongside `coturn` for the STUN/TURN services using [docker-compose](https://github.com/ineiti/fledger/blob/main/examples/docker-compose/docker-compose.signalling.yaml). Ideally I would like to include the STUN/TURN services directly in my signalling server, so all is in one binary. Currently I have a simple username/password authentication for the TURN.
> 
> So in the best case, I would be able to start a STUN server and give the username/password to start a TURN server.

Not currently possible, turn can only be run as a separate service, but you can control user authentication yourself, but I'll make this a plan

**Comment by mycrl** [comment]
> Thanks for your quick response. I currently run my WebRTC signalling server alongside `coturn` for the STUN/TURN services using [docker-compose](https://github.com/ineiti/fledger/blob/main/examples/docker-compose/docker-compose.signalling.yaml). Ideally I would like to include the STUN/TURN services directly in my signalling server, so all is in one binary. Currently I have a simple username/password authentication for the TURN.
> 
> So in the best case, I would be able to start a STUN server and give the username/password to start a TURN server.

hi, I have completed the split of the library so far, turn-server is an example of use.

**Comment by ineiti** [comment]
Wow - this is great news! I'll have to check it out!

I have to admit that I wanted to give it a try myself, but I got a new assignement in my job which leaves no room for my side-project for the moment :( But I hope to take it up in February again!
